import {strategy as D} from './strategy-data.mjs';
import {escapeHtml as E,chartGeometry,moneyM,safeIndex} from './strategy-utils.mjs';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const state={slide:0,device:D.devices[0].id,layer:'harness',sector:'government',region:'global',channel:'redington',scenario:'uae',metric:'revenue',year:4,facility:'without',quarter:0,infra:0,ma:0,insight:0};
const chapters=$$('.slide');let lastSourceButton=null;
const sourceButton=id=>'<button type="button" class="source-link" data-source="'+E(id)+'">'+E(id)+'</button>';
const citation=t=>'<p class="detail-source">'+E(t)+'</p>';
const status=t=>'<span class="status-badge">'+E(t)+'</span>';
const list=items=>'<ul class="clean-list">'+items.map(x=>'<li>'+E(x)+'</li>').join('')+'</ul>';
function bindPress(group,attr,current){$$(group+' ['+attr+']').forEach(b=>b.setAttribute('aria-pressed',String(b.getAttribute(attr)===String(current))));}
function announce(text){$('#navigation-announcement').textContent=text;}
function goTo(index,focus=false){const n=safeIndex(index,chapters.length),old=state.slide;state.slide=n;chapters.forEach((s,i)=>{s.hidden=i!==n;s.inert=i!==n;s.setAttribute('aria-hidden',String(i!==n));s.classList.toggle('active',i===n);if(i===n){s.style.setProperty('--ex',n>=old?'34px':'-34px');s.scrollTop=0;}});$('#slideNum').textContent=n+1;$('#slideTotal').textContent=chapters.length;$('#prev').disabled=n===0;$('#next').disabled=n===chapters.length-1;$('#chapter-select').value=chapters[n].id;$('#top-progress-fill').style.width=((n+1)/chapters.length*100)+'%';$$('#dots button').forEach((b,i)=>{b.classList.toggle('on',i===n);if(i===n)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});const activeDot=$$('#dots button')[n],dotStrip=$('#dots');if(activeDot&&dotStrip){dotStrip.scrollLeft=Math.max(0,activeDot.offsetLeft-(dotStrip.clientWidth-activeDot.offsetWidth)/2);}const title=chapters[n].querySelector('h1,h2');announce('Chapter '+(n+1)+' of '+chapters.length+': '+title.textContent.replace(/\s+/g,' ').trim());if(focus){title.tabIndex=-1;title.focus({preventScroll:true});}try{history.replaceState(null,'','#'+chapters[n].id);}catch{}return n;}
chapters.forEach((s,i)=>{const title=s.querySelector('h1,h2').textContent.replace(/\s+/g,' ').trim();const b=document.createElement('button');b.className='dot';b.type='button';b.setAttribute('aria-label','Chapter '+(i+1)+': '+title);b.addEventListener('click',()=>goTo(i,true));$('#dots').append(b);const o=document.createElement('option');o.value=s.id;o.textContent=String(i+1).padStart(2,'0')+' / '+title;$('#chapter-select').append(o);});
$('#prev').addEventListener('click',()=>goTo(state.slide-1,true));$('#next').addEventListener('click',()=>goTo(state.slide+1,true));$('#zoneL').addEventListener('click',()=>goTo(state.slide-1,true));$('#zoneR').addEventListener('click',()=>goTo(state.slide+1,true));$('#chapter-select').addEventListener('change',e=>goTo(chapters.findIndex(s=>s.id===e.target.value),true));
function renderDevice(){const d=D.devices.find(x=>x.id===state.device);$('#device-detail').innerHTML=status(d.status)+'<h3>'+E(d.title)+'</h3><p>'+E(d.body)+'</p><p class="gate-line"><strong>Before deployment</strong>'+E(d.gate)+'</p>'+citation(d.source+' · '+d.compute);bindPress('#device-controls','data-device',d.id);$('#linked-device').textContent=d.title;}
const coords=[[50,7],[83,22],[89,64],[69,88],[30,88],[11,63],[18,23]];D.devices.forEach((d,i)=>{const b=document.createElement('button');b.className='device-node';b.type='button';b.dataset.device=d.id;b.style.left=coords[i][0]+'%';b.style.top=coords[i][1]+'%';b.setAttribute('aria-label',d.title+' — '+d.status);b.setAttribute('aria-controls','device-detail');b.innerHTML='<span class="node-index">0'+(i+1)+'</span><img src="'+E(d.image)+'" width="78" height="65" alt="" decoding="async"><span class="device-name">'+E(d.title)+'</span>';b.addEventListener('click',()=>{state.device=d.id;renderDevice();});b.querySelector('img').addEventListener('error',()=>b.classList.add('image-unavailable'));$('#device-controls').append(b);});
function renderLayer(){const d=D.layers.find(x=>x.id===state.layer);$('#layer-detail').innerHTML='<span class="selector-label">'+E(d.kicker)+'</span><h3>'+E(d.title)+'</h3><p>'+E(d.body)+'</p>'+list(d.items)+citation(d.source);bindPress('#layer-controls','data-layer',d.id);}
D.layers.forEach(d=>{const b=document.createElement('button');b.className='layer-button';b.type='button';b.dataset.layer=d.id;b.setAttribute('aria-controls','layer-detail');b.innerHTML='<strong>'+E(d.title)+'</strong><small>'+E(d.kicker)+'</small>';b.addEventListener('click',()=>{state.layer=d.id;renderLayer();});$('#layer-controls').append(b);});
function renderSector(){const d=D.sectors.find(x=>x.id===state.sector);$('#sector-detail').innerHTML='<div><h3>'+E(d.title)+'</h3>'+status(d.status)+'<p class="tiny">'+E(d.source)+'</p></div><div><p>'+E(d.body)+'</p><p class="gate-line"><strong>Acceptance gate</strong>'+E(d.gate)+'</p></div>';bindPress('#sector-controls','data-sector',d.id);}
D.sectors.forEach(d=>{const b=document.createElement('button');b.type='button';b.dataset.sector=d.id;b.setAttribute('aria-controls','sector-detail');b.textContent=d.title;b.addEventListener('click',()=>{state.sector=d.id;renderSector();});$('#sector-controls').append(b);});
function renderChannel(){const d=D.channels.find(x=>x.id===state.channel);$('#channel-detail').innerHTML='<div class="channel-detail-meta">'+status(d.status)+'<span>'+E(d.role)+'</span></div><h3>'+E(d.name)+'</h3><span class="selector-label">'+E(d.scope)+'</span><p>'+E(d.body)+'</p><p class="gate-line"><strong>Scope & limitation</strong>'+E(d.limit)+'</p>'+citation(d.source);bindPress('#channel-controls','data-channel',d.id);}
function renderRegion(){const d=D.regions.find(x=>x.id===state.region);$('#region-detail').innerHTML='<h3>'+E(d.title)+'</h3><p>'+E(d.body)+'</p>';bindPress('#region-controls','data-region',d.id);const filtered=D.channels.filter(c=>state.region==='global'||c.regions.includes(state.region)||c.regions.includes('global'));$('#channel-controls').replaceChildren();filtered.forEach(c=>{const b=document.createElement('button');b.type='button';b.dataset.channel=c.id;b.textContent=c.name;b.setAttribute('aria-controls','channel-detail');b.addEventListener('click',()=>{state.channel=c.id;renderChannel();});$('#channel-controls').append(b);});if(!filtered.some(c=>c.id===state.channel))state.channel=filtered[0].id;renderChannel();}
D.regions.forEach(d=>{const b=document.createElement('button');b.type='button';b.dataset.region=d.id;b.textContent=d.title;b.setAttribute('aria-controls','region-detail channel-controls');b.addEventListener('click',()=>{state.region=d.id;renderRegion();});$('#region-controls').append(b);});
const modes={cloud:'Cloud deployment requires explicit tenant isolation, lawful data processing, identity controls and a verified hosting region. Cloud does not automatically mean sovereign.',onprem:'An on-premise configuration keeps processing inside an approved enterprise environment. Verify hardware, identity, model licensing, operations and customer acceptance for that installation.',hybrid:'A hybrid design routes each workload by data classification and approved boundaries. Private data must not cross into a public model endpoint without authorization and a lawful basis.',airgap:'Air-gapped deployment requires a genuinely isolated environment, validated local model/runtime, offline update procedures and auditable security controls. A source claim alone is not acceptance evidence.'};$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{bindPress('#mode-controls','data-mode',b.dataset.mode);$('#mode-detail').textContent=modes[b.dataset.mode];}));
function metricCard(label,value,note,em=false){return '<div class="metric-card'+(em?' emphasis':'')+'"><span class="label">'+E(label)+'</span><strong>'+E(value)+'</strong><small>'+E(note)+'</small></div>';}
function renderFinancial(){const s=D.model.scenarios[state.scenario],i=state.year,values=s[state.metric],g=chartGeometry(values);bindPress('#scenario-controls','data-scenario',s.id);bindPress('#metric-controls','data-metric',state.metric);bindPress('#year-controls','data-year',i);$('#scenario-condition').textContent=s.condition;const metricLabel={revenue:'Revenue · AED million',surplus:'Operating surplus / deficit · AED million',seats:'Seats · model-year count'}[state.metric];$('#chart-title').textContent=metricLabel;const ticks=g.ticks.map(v=>'<line x1="44" y1="'+g.y(v).toFixed(1)+'" x2="582" y2="'+g.y(v).toFixed(1)+'" stroke="#e2e9de"/><text x="33" y="'+(g.y(v)+4).toFixed(1)+'" text-anchor="end" fill="#657a6b" font-size="10">'+E(state.metric==='seats'?Math.round(v).toLocaleString('en-US'):v.toFixed(1))+'</text>').join('');const path=g.points.map((p,n)=>(n?'L':'M')+p.x.toFixed(1)+','+p.y.toFixed(1)).join(' '),area=path+' L'+g.points[4].x+','+g.baseline+' L'+g.points[0].x+','+g.baseline+' Z';const nodes=g.points.map((p,n)=>'<g><circle cx="'+p.x+'" cy="'+p.y+'" r="'+(n===i?7:4)+'" fill="'+(n===i?'#876426':'#0e7257')+'" stroke="white" stroke-width="2"/><text x="'+p.x+'" y="199" text-anchor="middle" fill="#657a6b" font-size="11">Y'+(n+1)+'</text></g>').join('');$('#financial-chart').innerHTML='<svg viewBox="0 0 600 205" role="img" aria-label="'+E(s.label+' '+metricLabel+' over model years1–5: '+values.join(', '))+'"><title>'+E(s.label+' — '+metricLabel)+'</title><desc>Management-prepared unaudited five-year forecast. See accessible annual table below.</desc>'+ticks+'<path d="'+area+'" fill="#e6f1e6" opacity="0.8"/><path d="'+path+'" fill="none" stroke="#0e7257" stroke-width="2.5"/>'+nodes+'</svg>';$('#financial-detail').innerHTML=metricCard('MODEL YEAR '+(i+1)+' · REVENUE',moneyM(s.revenue[i]),'Source-reported forecast',true)+metricCard('MODEL YEAR '+(i+1)+' · SEATS',s.seats[i].toLocaleString('en-US'),'Not current active users')+metricCard('OPERATING RESULT',moneyM(s.surplus[i]),'Revenue less fully-loaded cost')+metricCard('OPERATING BREAK-EVEN','Year '+s.breakEven,'First positive annual result; not cash payback');$('#financial-table').innerHTML='<table><caption>'+E(s.label)+' · S05 v13 · 3 September 2026 · unaudited</caption><thead><tr><th scope="col">Measure</th>'+[1,2,3,4,5].map(y=>'<th scope="col">Y'+y+'</th>').join('')+'</tr></thead><tbody>'+[['Seats','seats'],['Revenue · AED M','revenue'],['Fully-loaded cost · AED M','cost'],['Operating surplus / deficit · AED M','surplus']].map(([l,k])=>'<tr><th scope="row">'+l+'</th>'+s[k].map(v=>'<td>'+E(k==='seats'?v.toLocaleString('en-US'):v.toFixed(1))+'</td>').join('')+'</tr>').join('')+'</tbody></table>';renderFunding();}
for(let i=0;i<5;i++){const b=document.createElement('button');b.type='button';b.dataset.year=i;b.textContent='Inspect Y'+(i+1);b.setAttribute('aria-label','Inspect model Year '+(i+1));b.setAttribute('aria-controls','financial-detail');b.addEventListener('click',()=>{state.year=i;renderFinancial();});$('#year-controls').append(b);}
$$('[data-scenario]').forEach(b=>b.addEventListener('click',()=>{state.scenario=b.dataset.scenario;renderFinancial();}));$$('[data-metric]').forEach(b=>b.addEventListener('click',()=>{state.metric=b.dataset.metric;renderFinancial();}));
function renderFunding(){const f=D.model.funding[state.facility],s=D.model.scenarios[state.scenario];bindPress('#facility-controls','data-facility',state.facility);$('#funding-detail').innerHTML='<div class="funding-grid">'+metricCard('UAE BASE · MODELED CAPITAL',moneyM(f.capital,2),'Not an executed funding commitment')+metricCard('MODELED EQUITY PER PARTNER',moneyM(f.equityEach,2),'Contribution form and agreement pending')+metricCard('MODELED CONCESSIONAL FACILITY',state.facility==='with'?moneyM(f.facility,2):'None','Variant shown for UAE-only base')+'</div><p class="npv-note"><strong>UAE base / selected facility variant:</strong> Sovereign Partner NPV '+moneyM(f.partnerNpv,2)+' at 3.5%; AIREV NPV '+moneyM(f.airevNpv,2)+' at 10%.</p>'+(state.scenario==='international'?'<p class="npv-note"><strong>International upside / no-facility source card:</strong> Sovereign Partner NPV '+moneyM(s.partnerNpv)+'; AIREV NPV '+moneyM(s.airevNpv)+'. Rate attribution follows the named measures at 3.5% / 10%; the card does not restate methodology. Full-model confirmation remains pending.</p>':'')+'<p class="npv-note">Underlying cashflow definitions, valuation date and NPV horizon are not supplied. These participant values are not a current company valuation or a two-year return.</p>';}
$$('[data-facility]').forEach(b=>b.addEventListener('click',()=>{state.facility=b.dataset.facility;renderFunding();}));
function renderQuarter(){const q=D.quarters[state.quarter];bindPress('#quarter-controls','data-quarter',state.quarter);$('#quarter-detail').innerHTML='<div class="quarter-heading"><div><span class="selector-label">'+E(q.id+' · MONTHS '+q.months)+'</span><h3>'+E(q.title)+'</h3><p class="tiny">Accountable workstreams: '+E(q.owner)+'</p></div>'+status(q.status)+'</div><div class="quarter-columns"><div><h4>DELIVERABLES</h4><ul>'+q.deliverables.map(v=>'<li>'+E(v)+'</li>').join('')+'</ul></div><div><h4>DEPENDENCIES</h4><ul>'+q.dependencies.map(v=>'<li>'+E(v)+'</li>').join('')+'</ul></div><div><h4>MEASURABLE EXIT GATES</h4><ul>'+q.exitGates.map(v=>'<li>'+E(v)+'</li>').join('')+'</ul></div></div>'+citation(q.source+' · Proposed phase allocation; not approved dates.');}
D.quarters.forEach((q,i)=>{const b=document.createElement('button');b.className='quarter-button';b.type='button';b.dataset.quarter=i;b.setAttribute('aria-label',q.id+', months '+q.months+': '+q.title);b.setAttribute('aria-controls','quarter-detail');b.innerHTML='<strong>'+E(q.id)+'</strong><small>MONTHS '+E(q.months)+'</small><small>'+E(q.tag)+'</small>';b.addEventListener('click',()=>{state.quarter=i;renderQuarter();});$('#quarter-controls').append(b);});
function renderInfra(){const d=D.infra[state.infra];bindPress('#infra-controls','data-infra',state.infra);$('#comp-seq').innerHTML=status('Proposed sequence · conditional')+'<h3>'+E(d.title)+'</h3><p>'+E(d.body)+'</p>'+list(d.gates)+citation('U01; P01; S04 slide2. No completion or funding acceptance inferred.');}
D.infra.forEach((d,i)=>{const b=document.createElement('button');b.className='infra-button tl8-node';b.type='button';b.dataset.infra=i;b.dataset.scope='seq';b.dataset.pane='m'+(i+1);b.setAttribute('aria-controls','comp-seq');b.innerHTML='<strong>'+E(d.title)+'</strong><small>EXPLORE GATES →</small>';b.addEventListener('click',()=>{state.infra=i;renderInfra();});$('#infra-controls').append(b);});
function renderMa(){const d=D.ma[state.ma];bindPress('#ma-controls','data-ma',state.ma);$('#ma-detail').innerHTML=status('Potential · subject to completion')+'<h3>'+E(d.title)+'</h3><p>'+E(d.body)+'</p>'+list(d.gates)+citation(d.source);}
D.ma.forEach((d,i)=>{const b=document.createElement('button');b.type='button';b.dataset.ma=i;b.textContent=d.title;b.setAttribute('aria-controls','ma-detail');b.addEventListener('click',()=>{state.ma=i;renderMa();});$('#ma-controls').append(b);});
function renderInsight(){const d=D.insights[state.insight];bindPress('#insight-controls','data-insight',state.insight);$('#insight-detail').innerHTML='<span class="selector-label">LOCAL EVIDENCE GUIDE</span><h3>'+E(d.question)+'</h3><p>'+E(d.answer)+'</p>'+citation('Curated from the reviewed source register. No remote request, generated advice or legal certification.');}
D.insights.forEach((d,i)=>{const b=document.createElement('button');b.type='button';b.dataset.insight=i;b.textContent=d.question;b.setAttribute('aria-controls','insight-detail');b.addEventListener('click',()=>{state.insight=i;renderInsight();});$('#insight-controls').append(b);});
$('#source-register').innerHTML=Object.entries(D.sources).map(([id,s])=>'<article class="source-card"><h4>'+sourceButton(id)+' · '+E(s.title)+'</h4><small>'+E(s.date)+'</small><p>'+E(s.scope)+'</p></article>').join('');
function openSource(id,origin){const s=D.sources[id];if(!s)return;lastSourceButton=origin;$('#evidence-title').textContent=id+' · '+s.title;$('#evidence-body').innerHTML='<p><strong>'+E(s.date)+'</strong></p><p>'+E(s.scope)+'</p><p class="tiny">Private original names and locators are not embedded. Source-read does not mean independently verified or approved.</p>';$('#evidence-dialog').showModal();}
$('#evidence-dialog').addEventListener('close',()=>lastSourceButton?.focus({preventScroll:true}));
function openInsights(){goTo(chapters.findIndex(s=>s.id==='s9'),true);}$('#open-insights').addEventListener('click',openInsights);$('#airev-mic').addEventListener('click',openInsights);
document.addEventListener('click',e=>{const b=e.target.closest('[data-goto]');if(b){goTo(chapters.findIndex(s=>s.id===b.dataset.goto),true);return;}const src=e.target.closest('[data-source]');if(src){openSource(src.dataset.source,src);return;}if(e.target.closest('.wordmark')){e.preventDefault();goTo(0,true);}});
function wireTimeline(scope,compId){const nodes=$$('[data-scope="'+scope+'"]'),comp=document.getElementById(compId);if(!comp)return;function show(node){comp.querySelectorAll('.comp-pane').forEach(p=>p.hidden=p.dataset.pane!==node.dataset.pane);nodes.forEach(n=>{n.classList.toggle('on',n===node);n.setAttribute('aria-pressed',String(n===node));});}nodes.forEach(n=>{n.type='button';n.setAttribute('aria-controls',compId);n.setAttribute('aria-pressed',String(n.classList.contains('on')));['click','mouseenter','focus'].forEach(ev=>n.addEventListener(ev,()=>show(n)));});}
wireTimeline('rev','comp-rev');
const tip=$('#chartTip'),wrap=$('#chartWrap');if(tip&&wrap){$$('.barg').forEach(g=>{g.setAttribute('role','button');g.setAttribute('aria-label',g.dataset.tip);function show(){tip.textContent=g.dataset.tip;tip.style.opacity='1';tip.style.left='15px';tip.style.top='34px';}g.addEventListener('mouseenter',show);g.addEventListener('focus',show);g.addEventListener('click',show);g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show();}});g.addEventListener('mouseleave',()=>tip.style.opacity='0');g.addEventListener('blur',()=>tip.style.opacity='0');});}
const rovingGroups=['#device-controls','#layer-controls','#sector-controls','#region-controls','#channel-controls','#scenario-controls','#metric-controls','#year-controls','#facility-controls','#quarter-controls','#infra-controls','#ma-controls','#insight-controls','#mode-controls'];rovingGroups.forEach(selector=>$(selector).addEventListener('keydown',e=>{if(!['ArrowRight','ArrowDown','ArrowLeft','ArrowUp','Home','End'].includes(e.key))return;const buttons=Array.from($(selector).querySelectorAll('button')),i=buttons.indexOf(e.target);if(i<0)return;e.preventDefault();e.stopPropagation();const n=e.key==='Home'?0:e.key==='End'?buttons.length-1:(i+(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1)+buttons.length)%buttons.length;buttons[n].focus();buttons[n].click();}));
document.addEventListener('keydown',e=>{if($('#evidence-dialog').open||e.target.closest('input,textarea,select,[contenteditable=true],button,[role=button]'))return;const next=['ArrowRight','ArrowDown','PageDown',' '],prev=['ArrowLeft','ArrowUp','PageUp'];if(next.includes(e.key)){e.preventDefault();goTo(state.slide+1,true);}else if(prev.includes(e.key)){e.preventDefault();goTo(state.slide-1,true);}else if(e.key==='Home'){e.preventDefault();goTo(0,true);}else if(e.key==='End'){e.preventDefault();goTo(chapters.length-1,true);}});
let touchStart=null;document.addEventListener('touchstart',e=>{if(e.target.closest('button,select,input,textarea,[contenteditable],.table-scroll,dialog'))return;const t=e.changedTouches[0];touchStart={x:t.clientX,y:t.clientY,time:Date.now()};},{passive:true});document.addEventListener('touchend',e=>{if(!touchStart)return;const t=e.changedTouches[0],dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y,age=Date.now()-touchStart.time;touchStart=null;if(age<1000&&Math.abs(dx)>64&&Math.abs(dx)>Math.abs(dy)*1.5)goTo(state.slide+(dx<0?1:-1),true);},{passive:true});
document.addEventListener('focusin',e=>{if(e.target.matches('button,select,[contenteditable=true],[role=button]'))e.target.classList.add('input-focused');});
document.addEventListener('focusout',e=>e.target.classList?.remove('input-focused'));
renderDevice();renderLayer();renderSector();renderRegion();renderFinancial();renderQuarter();renderInfra();renderMa();renderInsight();
const initial=chapters.findIndex(s=>s.id===location.hash.slice(1));goTo(initial>=0?initial:0);document.documentElement.dataset.ready='true';
Object.defineProperty(window,'__strategyState',{get:()=>Object.freeze({...state,activeSection:chapters[state.slide].id}),configurable:false});
