/* ==========================================================================
   AIREV deck · "Ask the deck" — collapsible RAG assistant (chat.js)
   Vanilla ES2020, no build step, no dependencies, inline SVG icons.
   Backend: POST /api/chat (Vercel serverless function) → OnDemand chat session per
   visitor + knowledge-plugin RAG over the scrubbed data room. The document library
   (labels + OnDemand media ids) comes from ./library.json; downloads resolve via
   /api/media?id=<mediaId>.
   API    : window.AirevChat = { open, close, toggle, isOpen, ask, ready, library, docs, sessionId, backend }
   Events : document → chat:ready, chat:opened, chat:closed, chat:answered, chat:error
   ========================================================================== */
(function () {
  'use strict';

  /* ------------------------------------------------------------ configuration */
  const API_URL = '/api/chat';
  const MEDIA_URL = '/api/media';
  const LIB_URL = 'library.json';
  const INTRO = 'Ask me anything in the two-year strategy data room — answers are generated by OnDemand from the scrubbed documents, cite their sources, and every source can be downloaded.';
  const UNAVAILABLE = 'Document library unavailable';
  const SUGGESTIONS = [
    'What is the Series A2 valuation and how was it derived?',
    'What does the Qualcomm licence pay per device?',
    'Summarise the VVIP Sovereign JV economics',
    'What is the Tenstorrent Galaxy fleet and what does it cost?',
    'How does the Kairoswealth combination work?'
  ];
  const ICONS = {
    chat: '<path d="M4 5.5A2.5 2.5 0 0 1 6.5 3h11A2.5 2.5 0 0 1 20 5.5v8a2.5 2.5 0 0 1-2.5 2.5H9l-4.3 3.4A.6.6 0 0 1 4 19V5.5z"/>',
    close: '<path d="M6 6l12 12M18 6L6 18"/>',
    download: '<path d="M12 4v11m0 0l-4-4m4 4l4-4M5 19h14"/>',
    send: '<path d="M4 12l16-8-6 16-2.5-6.5L4 12z"/>',
    docs: '<path d="M7 4h7l4 4v12H7z"/><path d="M14 4v4h4M10 12h5M10 15h5"/>',
    warn: '<path d="M12 4l9 16H3L12 4zm0 6v4m0 3h.01"/>'
  };

  /* ---------------------------------------------------------------- helpers */
  const esc = (s) => String(s).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
  /* Confidentiality guard (defence in depth — the API already redacts). The deny-list is stored
     base64-encoded so the plaintext terms never appear in the repository: [base64(regex), flags]. */
  const DENY = [
    ['cHJlc2lkZW50aWFsXHMrY291cnQoPzpbJ+KAmV1zKT8=', 'gi'],
    ['b2ZmaWNlXHMrb2ZccytkZXZlbG9wbWVudFxzK2FmZmFpcnM=', 'gi'],
    ['XGJhdGhhclxi', 'gi'],
    ['XGJPREFcYg==', 'g']
  ].map(([b, f]) => new RegExp(decodeURIComponent(escape(atob(b))), f));
  const scrub = (s) => DENY.reduce((t, re) => t.replace(re, 'VVIP Sovereign JV'), String(s == null ? '' : s));
  const emit = (name, detail) => document.dispatchEvent(new CustomEvent(name, { detail }));
  const truncate = (s, n) => (s.length > n ? s.slice(0, n - 1).trimEnd() + '…' : s);
  const docType = (d) => String(d.type || (d.file || '').split('.').pop() || 'DOC').toUpperCase();
  const dlUrl = (d) => (d.mediaId ? `${MEDIA_URL}?id=${encodeURIComponent(d.mediaId)}` : d.file ? `${MEDIA_URL}?doc=${encodeURIComponent(d.id)}` : '#');
  const icon = (name, size = 16) =>
    `<svg class="chat-icon icon-${name}" data-testid="icon-${name}" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ICONS[name] || ''}</svg>`;
  const uid = () => (crypto.randomUUID ? crypto.randomUUID() : 'v' + Math.random().toString(36).slice(2) + Date.now().toString(36)).replace(/[^A-Za-z0-9_-]/g, '').slice(0, 48);
  function store(kind, key, val) {
    try {
      const s = kind === 'local' ? window.localStorage : window.sessionStorage;
      if (val === undefined) return s.getItem(key);
      if (val === null) s.removeItem(key); else s.setItem(key, val);
      return val;
    } catch (_) { return val === undefined ? null : val; }
  }
  const visitorId = () => store('local', 'airev-deck-visitor') || store('local', 'airev-deck-visitor', uid());
  let sessionId = store('session', 'airev-deck-session') || null;

  function h(tag, attrs = {}, children = []) {
    const n = document.createElement(tag);
    for (const [k, v] of Object.entries(attrs)) {
      if (v === undefined || v === null || v === false) continue;
      if (k === 'text') n.textContent = v;
      else if (k === 'html') n.innerHTML = v;
      else if (k === 'class') n.className = v;
      else n.setAttribute(k, v === true ? '' : String(v));
    }
    (Array.isArray(children) ? children : [children]).forEach((c) => { if (c != null) n.append(c); });
    return n;
  }

  /** Lightweight, safe Markdown → HTML for the assistant's answer (bold, bullets, paragraphs). */
  function renderMarkdown(text) {
    const lines = scrub(text).replace(/\r/g, '').split('\n');
    const out = [];
    let list = null;
    const inline = (s) => esc(s).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/`([^`]+)`/g, '<code>$1</code>');
    const flush = () => { if (list) { out.push('<ul>' + list.map((li) => `<li>${inline(li)}</li>`).join('') + '</ul>'); list = null; } };
    for (const raw of lines) {
      const line = raw.trim();
      if (!line) { flush(); continue; }
      const m = line.match(/^(?:[-*•]|\d+[.)])\s+(.*)$/);
      if (m) { (list = list || []).push(m[1]); continue; }
      flush();
      const head = line.match(/^#{1,4}\s+(.*)$/);
      out.push(head ? `<p><strong>${inline(head[1])}</strong></p>` : `<p>${inline(line)}</p>`);
    }
    flush();
    return out.join('');
  }

  /* --------------------------------------------------------------------- DOM */
  let panel, launcher, thread, docsEl, docsList, docsToggle, closeBtn, form, input, send, typingEl, suggestEl;
  let opened = false, introShown = false, noteShown = false, queue = Promise.resolve();
  let library = [], libError = null, readyResolve;
  const ready = new Promise((r) => { readyResolve = r; });
  const avatar = () => h('div', { class: 'avatar', 'data-testid': 'chat-avatar', 'aria-hidden': 'true', text: 'AI' });

  function build() {
    launcher = h('button', { id: 'chat-launcher', type: 'button', 'data-testid': 'chat-launcher', 'aria-label': 'Ask the deck', 'aria-haspopup': 'dialog', 'aria-controls': 'chat-panel' }, [
      h('span', { class: 'chat-launcher-icon', 'data-testid': 'chat-launcher-icon', html: icon('chat', 16) }),
      h('span', { class: 'chat-launcher-label', 'data-testid': 'chat-launcher-label', text: 'Ask the deck' })
    ]);
    docsToggle = h('button', { id: 'chat-docs-toggle', type: 'button', class: 'chat-btn', 'data-testid': 'chat-docs-toggle', 'aria-expanded': 'false', 'aria-controls': 'chat-docs', title: 'Browse the library',
      html: icon('docs', 14) + '<span class="chat-btn-label" data-testid="chat-docs-toggle-label">Documents</span>' });
    closeBtn = h('button', { id: 'chat-close', type: 'button', class: 'chat-btn icon', 'data-testid': 'chat-close', 'aria-label': 'Close assistant', title: 'Close (Esc)', html: icon('close', 16) });
    docsList = h('div', { class: 'chat-docs-list', 'data-testid': 'chat-docs-list' });
    docsEl = h('section', { id: 'chat-docs', class: 'chat-docs', 'data-testid': 'chat-docs', hidden: true, 'aria-label': 'Library documents' }, docsList);
    thread = h('div', { id: 'chat-thread', class: 'chat-thread', 'data-testid': 'chat-thread', role: 'log', 'aria-live': 'polite' });
    input = h('input', { id: 'chat-input', 'data-testid': 'chat-input', type: 'text', placeholder: 'Ask about valuation, partners, the JV, hardware…', autocomplete: 'off', 'aria-label': 'Your question' });
    send = h('button', { id: 'chat-send', 'data-testid': 'chat-send', type: 'submit', 'aria-label': 'Send', title: 'Send', html: icon('send', 16) });
    form = h('form', { id: 'chat-form', class: 'chat-form', 'data-testid': 'chat-form' }, [input, send]);
    typingEl = h('div', { class: 'msg assistant chat-typing', 'data-testid': 'chat-typing', 'aria-label': 'Assistant is typing' }, [
      avatar(), h('div', { class: 'bubble', 'data-testid': 'chat-typing-bubble' }, [0, 1, 2].map(() => h('span', { class: 'dot', 'data-testid': 'chat-typing-dot' })))
    ]);
    panel = h('aside', { id: 'chat-panel', class: 'chat-panel closed', 'data-testid': 'chat-panel', role: 'dialog', 'aria-modal': 'false', 'aria-label': 'Document assistant', 'aria-hidden': 'true' }, [
      h('header', { class: 'chat-head', 'data-testid': 'chat-head' }, [
        h('div', { class: 'chat-head-text', 'data-testid': 'chat-head-text' }, [
          h('h2', { class: 'chat-title', 'data-testid': 'chat-title', text: 'AIREV Insights' }),
          h('p', { class: 'chat-sub', 'data-testid': 'chat-subtitle', text: 'Document assistant · powered by OnDemand · answers cite the data room' })
        ]),
        h('div', { class: 'chat-head-actions', 'data-testid': 'chat-head-actions' }, [docsToggle, closeBtn])
      ]),
      docsEl,
      thread,
      h('footer', { class: 'chat-foot', 'data-testid': 'chat-foot' }, form)
    ]);
    document.body.append(launcher, panel);
  }

  function renderDocs() {
    docsList.replaceChildren();
    if (!library.length) return docsList.append(h('p', { class: 'chat-docs-empty', 'data-testid': 'chat-docs-empty', text: UNAVAILABLE }));
    library.forEach((d) => {
      const label = scrub(d.label || d.file || d.id);
      docsList.append(h('div', { class: 'chat-doc', 'data-testid': 'chat-doc', 'data-doc-id': d.id }, [
        h('span', { class: 'chat-badge', 'data-testid': 'chat-doc-type', text: docType(d) }),
        h('span', { class: 'chat-doc-main', 'data-testid': 'chat-doc-main' }, [
          h('span', { class: 'chat-doc-label', 'data-testid': 'chat-doc-label', title: label, text: label }),
          h('span', { class: 'chat-doc-meta', 'data-testid': 'chat-doc-expires', text: d.pages ? `${d.pages} pages · scrubbed extract · OnDemand media` : 'scrubbed extract · OnDemand media' })
        ]),
        h('a', { class: 'chat-dl', 'data-testid': 'chat-dl', href: dlUrl(d), target: '_blank', rel: 'noopener', download: true, title: `Download ${label}`, 'aria-label': `Download ${label}`, html: icon('download', 14) })
      ]));
    });
  }

  function scrollDown() { thread.scrollTop = thread.scrollHeight; }

  function addMsg(role, content) {
    const bubble = h('div', { class: 'bubble', 'data-testid': 'chat-bubble' }, content);
    const msg = h('div', { class: `msg ${role}`, 'data-testid': `chat-msg-${role}` }, role === 'assistant' ? [avatar(), bubble] : bubble);
    thread.append(msg);
    scrollDown();
    return msg;
  }

  function showIntro() {
    introShown = true;
    addMsg('assistant', h('p', { class: 'chat-lead', 'data-testid': 'chat-intro', text: INTRO }));
    suggestEl = h('div', { id: 'chat-suggestions', class: 'chat-suggestions', 'data-testid': 'chat-suggestions', role: 'group', 'aria-label': 'Suggested questions' },
      SUGGESTIONS.map((q) => h('button', { type: 'button', class: 'chat-suggestion', 'data-testid': 'chat-suggestion', text: q })));
    thread.append(suggestEl);
    if (libError) noteUnavailable();
    scrollDown();
  }

  function noteUnavailable() {
    if (noteShown) return;
    noteShown = true;
    addMsg('assistant', h('p', { class: 'chat-lead chat-warn', 'data-testid': 'chat-unavailable', text: `${UNAVAILABLE} — the document list could not be loaded; answers still work but downloads may be missing.` }));
  }

  function citeChip(c) {
    const label = truncate(scrub(c.label || 'Source'), 34) + (c.page ? ` · p.${c.page}` : '');
    const href = c.download || '#';
    return h('span', { class: 'chat-cite', 'data-testid': 'chat-cite', 'data-doc-id': c.docId || '' }, [
      h('a', { class: 'chat-cite-label', 'data-testid': 'chat-cite-label', href, target: '_blank', rel: 'noopener', title: `Open ${scrub(c.label)}`, text: label }),
      h('a', { class: 'chat-cite-dl', 'data-testid': 'chat-cite-dl', href, target: '_blank', rel: 'noopener', download: true, title: `Download ${scrub(c.label)}`, 'aria-label': `Download ${scrub(c.label)}`, html: icon('download', 12) })
    ]);
  }

  function renderAnswer(ans) {
    const parts = [h('div', { class: 'chat-answer', 'data-testid': 'chat-answer', html: renderMarkdown(ans.answer || '') })];
    if (ans.citations && ans.citations.length) parts.push(h('div', { class: 'chat-cites', 'data-testid': 'chat-cites' }, ans.citations.map(citeChip)));
    const meta = ans.metrics && ans.metrics.ragTimeSec != null ? `Grounded by OnDemand · retrieval ${Number(ans.metrics.ragTimeSec).toFixed(1)}s · ${ans.backend && ans.backend.endpointId ? ans.backend.endpointId.replace(/^predefined-/, '') : 'model'}` : 'Answered by OnDemand';
    parts.push(h('div', { class: 'chat-meta', 'data-testid': 'chat-meta', text: meta }));
    addMsg('assistant', parts);
  }

  function renderError(message) {
    addMsg('assistant', [
      h('p', { class: 'chat-lead chat-warn chat-error', 'data-testid': 'chat-error', html: icon('warn', 14) + ' ' + esc(scrub(message)) }),
      h('p', { class: 'chat-meta', 'data-testid': 'chat-error-hint', text: 'Please try again in a moment. If this persists, the OnDemand service may be unavailable.' })
    ]);
  }

  /* --------------------------------------------------------------- behaviour */
  function setBusy(b) { send.disabled = b; input.disabled = b; thread.setAttribute('aria-busy', String(b)); panel.classList.toggle('busy', b); }

  async function callApi(q) {
    const ctrl = new AbortController();
    const timer = setTimeout(() => ctrl.abort(), 90000);
    try {
      const res = await fetch(API_URL, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query: q, sessionId, visitorId: visitorId() }), signal: ctrl.signal });
      const data = await res.json().catch(() => ({}));
      if (!res.ok || !data.ok) { const e = new Error(data.error || `The assistant returned HTTP ${res.status}`); e.status = res.status; throw e; }
      return data;
    } finally { clearTimeout(timer); }
  }

  async function answer(q) {
    setBusy(true);
    if (suggestEl) { suggestEl.remove(); suggestEl = null; }
    addMsg('user', h('span', { class: 'chat-user-text', 'data-testid': 'chat-user-text', text: scrub(q) }));
    thread.append(typingEl);
    scrollDown();
    let result;
    try {
      const data = await callApi(q);
      if (data.sessionId && data.sessionId !== sessionId) { sessionId = data.sessionId; store('session', 'airev-deck-session', sessionId); }
      result = { question: q, ...data, answer: scrub(data.answer || ''), citations: (data.citations || []).map((c) => ({ ...c, label: scrub(c.label || '') })), empty: !(data.answer || '').trim() };
      typingEl.remove();
      renderAnswer(result);
      emit('chat:answered', result);
    } catch (err) {
      typingEl.remove();
      const msg = err && err.name === 'AbortError' ? 'The assistant took too long to respond.' : (err && err.message) || 'The assistant is unavailable right now.';
      if (err && (err.status === 404 || err.status === 400)) { sessionId = null; store('session', 'airev-deck-session', null); }
      renderError(msg);
      result = { question: q, error: msg, answer: '', citations: [], empty: true };
      emit('chat:error', result);
    }
    setBusy(false);
    return result;
  }

  /** Ask a question; answers are serialised so rapid calls never interleave in the thread. */
  function ask(question) {
    const q = String(question == null ? '' : question).trim();
    if (!q) return Promise.resolve(null);
    ensure();
    open();
    const run = queue.then(() => answer(q));
    queue = run.catch(() => {});
    return run;
  }

  function open() {
    ensure();
    if (opened) return;
    opened = true;
    panel.classList.remove('closed');
    panel.removeAttribute('aria-hidden');
    launcher.hidden = true;
    if (!introShown) showIntro();
    input.focus({ preventScroll: true });
    emit('chat:opened');
  }

  function close() {
    if (!opened) return;
    opened = false;
    launcher.hidden = false;
    if (panel.contains(document.activeElement)) launcher.focus({ preventScroll: true });
    panel.classList.add('closed');
    panel.setAttribute('aria-hidden', 'true');
    emit('chat:closed');
  }

  function bind() {
    launcher.addEventListener('click', open);
    closeBtn.addEventListener('click', close);
    docsToggle.addEventListener('click', () => {
      const show = docsEl.hidden;
      docsEl.hidden = !show;
      docsToggle.setAttribute('aria-expanded', String(show));
    });
    form.addEventListener('submit', (e) => {
      e.preventDefault();
      const q = input.value.trim();
      if (!q || send.disabled) return;
      input.value = '';
      ask(q);
    });
    thread.addEventListener('click', (e) => {
      const chip = e.target.closest('.chat-suggestion');
      if (chip) { ask(chip.textContent); input.focus({ preventScroll: true }); }
    });
    /* Escape closes the panel and is swallowed in the capture phase so the deck's own Escape handler never sees it. */
    window.addEventListener('keydown', (e) => {
      if (e.key !== 'Escape' || !opened) return;
      e.stopImmediatePropagation();
      e.preventDefault();
      close();
    }, { capture: true });
  }

  async function load() {
    try {
      const res = await fetch(LIB_URL);
      if (!res.ok) throw new Error(`${LIB_URL} responded ${res.status}`);
      const data = await res.json();
      library = Array.isArray(data && data.docs) ? data.docs : [];
    } catch (err) {
      libError = (err && err.message) || String(err);
      library = [];
      if (introShown) noteUnavailable();
    }
    renderDocs();
    const detail = { docs: library.length, backend: 'ondemand', ...(libError ? { error: libError } : {}) };
    readyResolve(detail);
    emit('chat:ready', detail);
  }

  function init() {
    if (panel || !document.body) return;
    build(); bind(); load();
    /* Deep link: ?ask=<question> opens the assistant and asks immediately (used for share links and tests). */
    try {
      const q = new URLSearchParams(location.search).get('ask');
      if (q && q.trim()) setTimeout(() => ask(q.trim()), 400);
    } catch (_) { /* ignore */ }
  }
  const ensure = () => { if (!panel) init(); };

  /* ------------------------------------------------------------- public API */
  window.AirevChat = {
    open, close, toggle: () => (opened ? close() : open()), isOpen: () => opened, ask, ready,
    backend: 'ondemand',
    sessionId: () => sessionId,
    get library() { return library; },
    docs: () => library.map((d) => ({ id: d.id, label: scrub(d.label || d.file || d.id), url: dlUrl(d), type: docType(d), mediaId: d.mediaId || null }))
  };

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
